/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;

/**
 *
 * @author jmari
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    ControladorBanco banco;
    ControladorCuenta cuenta;
    DefaultTableModel dtmCuentas;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        llenarCombos();
        banco = new ControladorBanco();
        cuenta = new ControladorCuenta();
        dtmCuentas = new DefaultTableModel(new Object[] {"Número", "Tipo", "Saldo", "Titular"}, 0);
        tblCuentas.setModel(dtmCuentas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JTabbedPane();
        pnlAdminClientes = new javax.swing.JPanel();
        lblTituloAdminClientes = new javax.swing.JLabel();
        lblDocumentoCliente = new javax.swing.JLabel();
        txtDocumentoCliente = new javax.swing.JTextField();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblCorreoCliente = new javax.swing.JLabel();
        txtCorreoCliente = new javax.swing.JTextField();
        lblTelefonoCliente = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        lblFechaNacimientoCliente = new javax.swing.JLabel();
        lblDiaNacimientoCliente = new javax.swing.JLabel();
        lblMesNacimientoCliente = new javax.swing.JLabel();
        lblAnioNacimientoCliente = new javax.swing.JLabel();
        cbxDiaNacimientoCliente = new javax.swing.JComboBox<>();
        cbxMesNacimientoCliente = new javax.swing.JComboBox<>();
        cbxAnioNacimientoCliente = new javax.swing.JComboBox<>();
        lblEstaturaCliente = new javax.swing.JLabel();
        txtEstaturaCliente = new javax.swing.JTextField();
        lblTipoCliente = new javax.swing.JLabel();
        cbxTipoCliente = new javax.swing.JComboBox<>();
        btnCrearCliente = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        pnlAdminCuentas = new javax.swing.JPanel();
        lblTituloAdminCuentas = new javax.swing.JLabel();
        cbxTitularCuenta = new javax.swing.JComboBox<>();
        lblTitularCuenta = new javax.swing.JLabel();
        lblNumeroCuenta = new javax.swing.JLabel();
        lblTipoCuenta = new javax.swing.JLabel();
        lblSaldoCuenta = new javax.swing.JLabel();
        lblClaveCuenta = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        cbxTipoCuenta = new javax.swing.JComboBox<>();
        txtSaldoCuenta = new javax.swing.JTextField();
        txtClaveCuenta = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuentas = new javax.swing.JTable();
        btnCrearCuenta = new javax.swing.JButton();
        btnBuscarCuenta = new javax.swing.JButton();
        btnActualizarCuenta = new javax.swing.JButton();
        btnEliminarCuenta = new javax.swing.JButton();
        pnlTransacciones = new javax.swing.JPanel();
        lblTituloTransaccion = new javax.swing.JLabel();
        lblNumeroCuentaTransaccion = new javax.swing.JLabel();
        lblCantidadTransaccion = new javax.swing.JLabel();
        txtNumeroCuentaTransaccion = new javax.swing.JTextField();
        txtCantidadTransaccion = new javax.swing.JTextField();
        btnConsignar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        lblTituloPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTituloAdminClientes.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTituloAdminClientes.setText("Administrar Clientes");

        lblDocumentoCliente.setText("Documento");

        lblNombreCliente.setText("Nombre");

        lblCorreoCliente.setText("Correo");

        lblTelefonoCliente.setText("Teléfono");

        lblFechaNacimientoCliente.setText("Fecha Nacimiento");

        lblDiaNacimientoCliente.setText("Dia");

        lblMesNacimientoCliente.setText("Mes");

        lblAnioNacimientoCliente.setText("Año");

        lblEstaturaCliente.setText("Estatura");

        lblTipoCliente.setText("Tipo de Cliente");

        cbxTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona Natural", "Persona Jurídica" }));

        btnCrearCliente.setText("Crear");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnActualizarCliente.setText("Actualizar");
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminClientesLayout = new javax.swing.GroupLayout(pnlAdminClientes);
        pnlAdminClientes.setLayout(pnlAdminClientesLayout);
        pnlAdminClientesLayout.setHorizontalGroup(
            pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminClientesLayout.createSequentialGroup()
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminClientesLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblTipoCliente)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTipoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlAdminClientesLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombreCliente)
                            .addComponent(lblDocumentoCliente)
                            .addComponent(lblCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefonoCliente)
                            .addComponent(lblFechaNacimientoCliente)
                            .addComponent(lblEstaturaCliente))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDocumentoCliente)
                            .addComponent(txtNombreCliente)
                            .addComponent(txtCorreoCliente)
                            .addComponent(txtTelefonoCliente)
                            .addGroup(pnlAdminClientesLayout.createSequentialGroup()
                                .addComponent(cbxDiaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMesNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAnioNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 88, Short.MAX_VALUE))
                            .addComponent(txtEstaturaCliente)))
                    .addGroup(pnlAdminClientesLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(lblDiaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(lblMesNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(lblAnioNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminClientesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTituloAdminClientes)
                        .addGap(95, 95, 95)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        pnlAdminClientesLayout.setVerticalGroup(
            pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAdminClientes)
                .addGap(53, 53, 53)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumentoCliente)
                    .addComponent(txtDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminClientesLayout.createSequentialGroup()
                        .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreoCliente)
                            .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminClientesLayout.createSequentialGroup()
                        .addComponent(btnBuscarCliente)
                        .addGap(3, 3, 3)))
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoCliente)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(btnActualizarCliente)
                .addGap(5, 5, 5)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaNacimientoCliente)
                    .addComponent(lblMesNacimientoCliente)
                    .addComponent(lblAnioNacimientoCliente))
                .addGap(11, 11, 11)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimientoCliente)
                    .addComponent(cbxDiaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMesNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAnioNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCliente))
                .addGap(27, 27, 27)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstaturaCliente)
                    .addComponent(txtEstaturaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlAdminClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoCliente)
                    .addComponent(cbxTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("Admin Clientes", pnlAdminClientes);

        lblTituloAdminCuentas.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTituloAdminCuentas.setText("Administrar Cuentas");

        lblTitularCuenta.setText("Titular");

        lblNumeroCuenta.setText("Número");

        lblTipoCuenta.setText("Tipo");

        lblSaldoCuenta.setText("Saldo");

        lblClaveCuenta.setText("Clave");

        cbxTipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ahorros", "Corriente" }));

        tblCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCuentas);

        btnCrearCuenta.setText("Crear");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        btnBuscarCuenta.setText("Buscar");
        btnBuscarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCuentaActionPerformed(evt);
            }
        });

        btnActualizarCuenta.setText("Actualizar");
        btnActualizarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCuentaActionPerformed(evt);
            }
        });

        btnEliminarCuenta.setText("Eliminar");
        btnEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminCuentasLayout = new javax.swing.GroupLayout(pnlAdminCuentas);
        pnlAdminCuentas.setLayout(pnlAdminCuentasLayout);
        pnlAdminCuentasLayout.setHorizontalGroup(
            pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminCuentasLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(lblTituloAdminCuentas)
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminCuentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumeroCuenta)
                    .addComponent(lblTipoCuenta)
                    .addComponent(lblSaldoCuenta)
                    .addComponent(lblClaveCuenta)
                    .addComponent(lblTitularCuenta))
                .addGap(18, 18, 18)
                .addGroup(pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxTipoCuenta, 0, 277, Short.MAX_VALUE)
                    .addComponent(txtNumeroCuenta)
                    .addComponent(txtSaldoCuenta)
                    .addComponent(txtClaveCuenta)
                    .addComponent(cbxTitularCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151))
            .addGroup(pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminCuentasLayout.createSequentialGroup()
                    .addContainerGap(98, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );
        pnlAdminCuentasLayout.setVerticalGroup(
            pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminCuentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAdminCuentas)
                .addGroup(pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminCuentasLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroCuenta)
                            .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoCuenta)
                            .addComponent(cbxTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSaldoCuenta)
                            .addComponent(txtSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClaveCuenta)
                            .addComponent(txtClaveCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAdminCuentasLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnCrearCuenta)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCuenta)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarCuenta)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCuenta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTitularCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitularCuenta))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(pnlAdminCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminCuentasLayout.createSequentialGroup()
                    .addContainerGap(324, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        pnlPrincipal.addTab("Admin Cuentas", pnlAdminCuentas);

        lblTituloTransaccion.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTituloTransaccion.setText("Realizar Transacción");

        lblNumeroCuentaTransaccion.setText("Número de Cuenta");

        lblCantidadTransaccion.setText("Cantidad");

        btnConsignar.setText("Consignar");
        btnConsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsignarActionPerformed(evt);
            }
        });

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTransaccionesLayout = new javax.swing.GroupLayout(pnlTransacciones);
        pnlTransacciones.setLayout(pnlTransaccionesLayout);
        pnlTransaccionesLayout.setHorizontalGroup(
            pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransaccionesLayout.createSequentialGroup()
                .addGroup(pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTransaccionesLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(lblTituloTransaccion))
                    .addGroup(pnlTransaccionesLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCantidadTransaccion)
                            .addComponent(lblNumeroCuentaTransaccion))
                        .addGap(27, 27, 27)
                        .addGroup(pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlTransaccionesLayout.createSequentialGroup()
                                .addComponent(btnConsignar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNumeroCuentaTransaccion)
                                .addComponent(txtCantidadTransaccion, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)))))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        pnlTransaccionesLayout.setVerticalGroup(
            pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransaccionesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTransaccionesLayout.createSequentialGroup()
                        .addComponent(lblTituloTransaccion)
                        .addGap(73, 73, 73))
                    .addGroup(pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumeroCuentaTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumeroCuentaTransaccion)))
                .addGap(18, 18, 18)
                .addGroup(pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadTransaccion)
                    .addComponent(txtCantidadTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(pnlTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsignar)
                    .addComponent(btnRetirar))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("Transacciones", pnlTransacciones);

        lblTituloPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTituloPrincipal.setText("Banco U. Caldas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloPrincipal)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTituloPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        // TODO add your handling code here:
        crearCliente();
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        buscarCliente();
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        borrarCliente();
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
        // TODO add your handling code here:
        actualizarCliente();
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
        crearCuenta();
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnBuscarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCuentaActionPerformed
        // TODO add your handling code here:
        buscarCuenta();
    }//GEN-LAST:event_btnBuscarCuentaActionPerformed

    private void btnActualizarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCuentaActionPerformed
        // TODO add your handling code here:
        actualizarCuenta();
    }//GEN-LAST:event_btnActualizarCuentaActionPerformed

    private void btnEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCuentaActionPerformed
        // TODO add your handling code here:
        borrarCuenta();
    }//GEN-LAST:event_btnEliminarCuentaActionPerformed

    private void btnConsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsignarActionPerformed
        // TODO add your handling code here:
        consignarDinero();
    }//GEN-LAST:event_btnConsignarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        // TODO add your handling code here:
        retirarDinero();
    }//GEN-LAST:event_btnRetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnActualizarCuenta;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarCuenta;
    private javax.swing.JButton btnConsignar;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarCuenta;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JComboBox<String> cbxAnioNacimientoCliente;
    private javax.swing.JComboBox<String> cbxDiaNacimientoCliente;
    private javax.swing.JComboBox<String> cbxMesNacimientoCliente;
    private javax.swing.JComboBox<String> cbxTipoCliente;
    private javax.swing.JComboBox<String> cbxTipoCuenta;
    private javax.swing.JComboBox<String> cbxTitularCuenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnioNacimientoCliente;
    private javax.swing.JLabel lblCantidadTransaccion;
    private javax.swing.JLabel lblClaveCuenta;
    private javax.swing.JLabel lblCorreoCliente;
    private javax.swing.JLabel lblDiaNacimientoCliente;
    private javax.swing.JLabel lblDocumentoCliente;
    private javax.swing.JLabel lblEstaturaCliente;
    private javax.swing.JLabel lblFechaNacimientoCliente;
    private javax.swing.JLabel lblMesNacimientoCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumeroCuenta;
    private javax.swing.JLabel lblNumeroCuentaTransaccion;
    private javax.swing.JLabel lblSaldoCuenta;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JLabel lblTipoCliente;
    private javax.swing.JLabel lblTipoCuenta;
    private javax.swing.JLabel lblTitularCuenta;
    private javax.swing.JLabel lblTituloAdminClientes;
    private javax.swing.JLabel lblTituloAdminCuentas;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JLabel lblTituloTransaccion;
    private javax.swing.JPanel pnlAdminClientes;
    private javax.swing.JPanel pnlAdminCuentas;
    private javax.swing.JTabbedPane pnlPrincipal;
    private javax.swing.JPanel pnlTransacciones;
    private javax.swing.JTable tblCuentas;
    private javax.swing.JTextField txtCantidadTransaccion;
    private javax.swing.JPasswordField txtClaveCuenta;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDocumentoCliente;
    private javax.swing.JTextField txtEstaturaCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtNumeroCuentaTransaccion;
    private javax.swing.JTextField txtSaldoCuenta;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables

    private void llenarCombos() {
        // Día de nacimiento
        for (int i = 31; i >= 1; i--) {
            cbxDiaNacimientoCliente.addItem(i + "");
        }
        
        // Mes de nacimiento
        for (int i = 12; i >= 1; i--) {
            cbxMesNacimientoCliente.addItem(i + "");
        }
        
        // Año de nacimiento
        for (int i = LocalDate.now().getYear(); i >= 1940; i--) {
            cbxAnioNacimientoCliente.addItem(i + "");
        }
    }

    private void crearCliente() {
        
        if (validarCamposCliente()) {
            String tipo = cbxTipoCliente.getSelectedItem().toString();
            String documento = txtDocumentoCliente.getText();
            String nombre = txtNombreCliente.getText();
            String correo = txtCorreoCliente.getText();
            String telefono = txtTelefonoCliente.getText();
            int diaNacimiento = Integer.parseInt(cbxDiaNacimientoCliente.getSelectedItem().toString());
            int mesNacimiento = Integer.parseInt(cbxMesNacimientoCliente.getSelectedItem().toString());
            int anioNacimiento = Integer.parseInt(cbxAnioNacimientoCliente.getSelectedItem().toString());
            double estatura = Double.parseDouble(txtEstaturaCliente.getText());
            
            Cliente cliente = banco.crearCliente(tipo, documento, nombre, correo, telefono, diaNacimiento, mesNacimiento, anioNacimiento, estatura);
            if (cliente != null) {
                JOptionPane.showMessageDialog(this, "Cliente creado correctamente...");
                System.out.println(cliente.getDocumento() + " - " + cliente.getNombre());
                actualizarListaTitulares();
                limpiarCamposCliente();
            } else {
                JOptionPane.showMessageDialog(this, "Error al crear el cliente... Puede que ya exista.");
            }
        }
        
    }

    private void buscarCliente() {
        Cliente cliente = banco.buscarCliente(txtDocumentoCliente.getText());
        
        if (cliente != null) {
            txtNombreCliente.setText(cliente.getNombre());
            txtCorreoCliente.setText(cliente.getCorreo());
            txtTelefonoCliente.setText(cliente.getTelefono());
            txtEstaturaCliente.setText(cliente.getEstatura() + "");
            cbxTipoCliente.setSelectedItem(cliente.getTipo());
            cbxDiaNacimientoCliente.setSelectedItem(cliente.getFechaNacimiento().getDayOfMonth());
            cbxMesNacimientoCliente.setSelectedItem(cliente.getFechaNacimiento().getMonthValue());
            cbxAnioNacimientoCliente.setSelectedItem(cliente.getFechaNacimiento().getYear());
        } else {
            JOptionPane.showMessageDialog(this, "El cliente no existe...");
        }
    }

    private void limpiarCamposCliente() {
        txtDocumentoCliente.setText("");
        txtNombreCliente.setText("");
        txtCorreoCliente.setText("");
        txtTelefonoCliente.setText("");
        txtEstaturaCliente.setText("");
        cbxTipoCliente.setSelectedIndex(0);
        cbxDiaNacimientoCliente.setSelectedIndex(0);
        cbxMesNacimientoCliente.setSelectedIndex(0);
        cbxAnioNacimientoCliente.setSelectedIndex(0);
    }

    private void borrarCliente() {
        boolean clienteEliminado = banco.borrarCliente(txtDocumentoCliente.getText());
        
        if (clienteEliminado) {
            JOptionPane.showMessageDialog(this, "El cliente ha sido eliminado...");
            actualizarListaTitulares();
            limpiarCamposCliente();
        } else {
            JOptionPane.showMessageDialog(this, "El cliente no existe...");
        }
    }

    private void actualizarCliente() {
        if (validarCamposCliente()) {
            String tipo = cbxTipoCliente.getSelectedItem().toString();
            String documento = txtDocumentoCliente.getText();
            String nombre = txtNombreCliente.getText();
            String correo = txtCorreoCliente.getText();
            String telefono = txtTelefonoCliente.getText();
            int diaNacimiento = Integer.parseInt(cbxDiaNacimientoCliente.getSelectedItem().toString());
            int mesNacimiento = Integer.parseInt(cbxMesNacimientoCliente.getSelectedItem().toString());
            int anioNacimiento = Integer.parseInt(cbxAnioNacimientoCliente.getSelectedItem().toString());
            double estatura = Double.parseDouble(txtEstaturaCliente.getText());
            
            boolean clienteActualizado = banco.actualizarCliente(tipo, documento, nombre, correo, telefono, diaNacimiento, mesNacimiento, anioNacimiento, estatura);
            if (clienteActualizado) {
                JOptionPane.showMessageDialog(this, "Cliente actualizado correctamente...");
                actualizarListaTitulares();
                limpiarCamposCliente();
            } else {
                JOptionPane.showMessageDialog(this, "Error al editar el cliente... Puede que no exista.");
            }
        }
    }
    
    public boolean validarCamposCliente() {
        if (txtDocumentoCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El documento es obligatorio");
            return false;
        } else if (txtNombreCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio");
            return false;
        } else if (txtCorreoCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El correo es obligatorio");
            return false;
        } else if (txtTelefonoCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El teléfono es obligatorio");
            return false;
        } else if (txtEstaturaCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "La estatura es obligatoria");
            return false;
        } else {
            return true;
        }
    }

    private void actualizarListaTitulares() {
        cbxTitularCuenta.removeAllItems();
        
        for (Cliente cliente : banco.getBanco().getLstClientes()) {
            cbxTitularCuenta.addItem(cliente.getNombre());
        }
        
    }
    
    private void listarCuentas() {
        DefaultTableModel modelo = (DefaultTableModel) tblCuentas.getModel();
        modelo.setRowCount(0);

        for (Cuenta c : banco.listarCuentas()) {
            modelo.addRow(new Object[]{
                c.getNumero(),
                c.getTipo(),
                c.getSaldo(),
                c.getTitular().getNombre()
            });
        }
    }
    
    private Cliente obtenerTitularSeleccionado() {
        int indice = cbxTitularCuenta.getSelectedIndex();

        if (indice == -1) {
            return null;
        }

        return banco.getBanco().getLstClientes().get(indice);
    }
    
    private boolean validarCamposCuenta() {
        if (txtNumeroCuenta.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El número de cuenta es obligatorio");
            return false;
        }

        if (txtSaldoCuenta.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El saldo es obligatorio");
            return false;
        }

        if (txtClaveCuenta.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "La clave es obligatoria");
            return false;
        }

        if (cbxTitularCuenta.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un titular");
            return false;
        }

        return true;
    }
    
    private void limpiarCamposCuenta() {
        txtNumeroCuenta.setText("");
        txtSaldoCuenta.setText("");
        txtClaveCuenta.setText("");
        cbxTipoCuenta.setSelectedIndex(0);

        if (cbxTitularCuenta.getItemCount() > 0) {
            cbxTitularCuenta.setSelectedIndex(0);
        }
    }
    
    private void crearCuenta() {
        if (validarCamposCuenta()) {
            try {
                int numero = Integer.parseInt(txtNumeroCuenta.getText());
                String tipo = cbxTipoCuenta.getSelectedItem().toString();
                double saldo = Double.parseDouble(txtSaldoCuenta.getText());
                String clave = new String(txtClaveCuenta.getPassword());
                Cliente titular = obtenerTitularSeleccionado();

                Cuenta nuevaCuenta = banco.crearCuenta(numero, tipo, saldo, clave, titular);

                if (nuevaCuenta != null) {
                    JOptionPane.showMessageDialog(this, "Cuenta creada correctamente");
                    listarCuentas();
                    limpiarCamposCuenta();
                } else {
                    JOptionPane.showMessageDialog(this, "La cuenta ya existe");
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Número o saldo inválido");
            }
        }
    }
    
    private void buscarCuenta() {
        try {
            int numero = Integer.parseInt(txtNumeroCuenta.getText());

            Cuenta cuentaEncontrada = banco.buscarCuenta(numero);

            if (cuentaEncontrada != null) {
                cbxTipoCuenta.setSelectedItem(cuentaEncontrada.getTipo());
                txtSaldoCuenta.setText(cuentaEncontrada.getSaldo() + "");
                txtClaveCuenta.setText(cuentaEncontrada.getClave());

                int indice = banco.getBanco().getLstClientes().indexOf(cuentaEncontrada.getTitular());
                cbxTitularCuenta.setSelectedIndex(indice);

            } else {
                JOptionPane.showMessageDialog(this, "La cuenta no existe");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de cuenta válido");
        }
    }
    
    private void actualizarCuenta() {
        if (validarCamposCuenta()) {
            try {
                int numero = Integer.parseInt(txtNumeroCuenta.getText());
                String tipo = cbxTipoCuenta.getSelectedItem().toString();
                double saldo = Double.parseDouble(txtSaldoCuenta.getText());
                String clave = new String(txtClaveCuenta.getPassword());
                Cliente titular = obtenerTitularSeleccionado();

                boolean actualizada = banco.actualizarCuenta(numero, tipo, saldo, clave, titular);

                if (actualizada) {
                    JOptionPane.showMessageDialog(this, "Cuenta actualizada correctamente");
                    listarCuentas();
                    limpiarCamposCuenta();
                } else {
                    JOptionPane.showMessageDialog(this, "La cuenta no existe");
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Número o saldo inválido");
            }
        }
    }
    
    private void borrarCuenta() {
        try {
            int numero = Integer.parseInt(txtNumeroCuenta.getText());

            boolean eliminada = banco.borrarCuenta(numero);

            if (eliminada) {
                JOptionPane.showMessageDialog(this, "Cuenta eliminada correctamente");
                listarCuentas();
                limpiarCamposCuenta();
            } else {
                JOptionPane.showMessageDialog(this, "La cuenta no existe");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de cuenta válido");
        }
    }

    private void consignarDinero() {
        if (validarCamposTransaccion()) {
            try {
                int numero = Integer.parseInt(txtNumeroCuentaTransaccion.getText());
                double cantidad = Double.parseDouble(txtCantidadTransaccion.getText());

                boolean consignado = banco.consignarDinero(numero, cantidad);

                if (consignado) {
                    JOptionPane.showMessageDialog(this, "Transacción realizada correctamente");
                    listarCuentas();
                    limpiarCamposTransaccion();
                } else {
                    JOptionPane.showMessageDialog(this, "La cuenta no existe");
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Ocurrió algún error al realizar la transacción");
            }
        }
    }
    
    private boolean validarCamposTransaccion() {
        if (txtNumeroCuentaTransaccion.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El número de cuenta es obligatorio");
            return false;
        }

        if (txtCantidadTransaccion.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "La cantidad es obligatoria");
            return false;
        }

        return true;
    }
    
    private void limpiarCamposTransaccion() {
        txtNumeroCuentaTransaccion.setText("");
        txtCantidadTransaccion.setText("");
        
    }

    private void retirarDinero() {
        if (validarCamposTransaccion()) {
            try {
                int numero = Integer.parseInt(txtNumeroCuentaTransaccion.getText());
                double cantidad = Double.parseDouble(txtCantidadTransaccion.getText());

                boolean retirado = banco.retirarDinero(numero, cantidad);

                if (retirado) {
                    JOptionPane.showMessageDialog(this, "Transacción realizada correctamente");
                    listarCuentas();
                    limpiarCamposTransaccion();
                } else {
                    JOptionPane.showMessageDialog(this, "La cuenta no existe o los fondos son insuficientes");
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Ocurrió algún error al realizar la transacción");
            }
        }
    }
}
